Repository UQdeco2800/2022-studio-3, pull requests merged in 2022-10, with the labels that each got.

#177 Team 6 sprint 3: Building + path generation
  source/core/assets/configs/buildingSpecifications.json
  source/core/src/main/com/deco2800/game/areas/AtlantisGameArea.java
  source/core/src/main/com/deco2800/game/areas/MapGenerator/Buildings/Building.java
  source/core/src/main/com/deco2800/game/areas/MapGenerator/Buildings/BuildingGenerator.java
  source/core/src/main/com/deco2800/game/areas/MapGenerator/Buildings/BuildingSpecification.java
  source/core/src/main/com/deco2800/game/areas/MapGenerator/Buildings/CityRow.java
  source/core/src/main/com/deco2800/game/areas/MapGenerator/Coordinate.java
  source/core/src/main/com/deco2800/game/areas/MapGenerator/MapGenerator.java
  source/core/src/main/com/deco2800/game/areas/MapGenerator/ResourceGenerator.java
  source/core/src/main/com/deco2800/game/areas/MapGenerator/ResourceSpecification.java
  source/core/src/main/com/deco2800/game/areas/MapGenerator/pathBuilding/PathGenerator.java
  source/core/src/main/com/deco2800/game/components/weather/WeatherIcon.java
  source/core/src/main/com/deco2800/game/components/weather/WeatherIconProperties.java
  source/core/src/main/com/deco2800/game/map/MapComponent.java
  source/core/src/main/com/deco2800/game/map/MapService.java
  source/core/src/test/com/deco2800/game/areas/MapGenerator/MapGeneratorTest.java
  source/core/src/test/com/deco2800/game/components/weather/WeatherIconDisplayTest.java
  source/core/src/test/com/deco2800/game/map/MapServiceTest.java
  source/desktop/replay_pid8292.log
Labels: team 6, Sprint 3

#195 Team 6 Sprint 3 Final - Updated City Layout and Buildings
  source/cityMap.txt
  source/core/assets/configs/buildingSpecifications.json
  source/core/assets/images/barracks_level_1.0.png-autosave.kra
  source/core/assets/images/blacksmith.png
  source/core/assets/images/blacksmith.png-autosave.kra
  source/core/assets/images/city_tile.png
  source/core/assets/images/connector_ew.png
  source/core/assets/images/connector_ns.png
  source/core/assets/images/ew_gate.atlas
  source/core/assets/images/ew_gate.png
  source/core/assets/images/farm.png
  source/core/assets/images/farm.png-autosave.kra
  source/core/assets/images/gate_ew_closed.png
  source/core/assets/images/gate_ew_open.png
  source/core/assets/images/gate_ns_closed.png
  source/core/assets/images/gate_ns_open.png
  source/core/assets/images/highlightedBlacksmith.png
  source/core/assets/images/highlightedFarm.png
  source/core/assets/images/highlightedLeftFacingLibrary.png
  source/core/assets/images/highlightedLibrary.png
  source/core/assets/images/library.png
  source/core/assets/images/library.png-autosave.kra
  source/core/assets/images/ns_gate.atlas
  source/core/assets/images/ns_gate.png
  source/core/assets/images/pathTile.png
  source/core/assets/images/rightFacingLibrary.png
  source/core/assets/images/wall_pillar.png
  source/core/src/main/com/deco2800/game/areas/AtlantisGameArea.java
  source/core/src/main/com/deco2800/game/areas/MapGenerator/Buildings/Building.java
  source/core/src/main/com/deco2800/game/areas/MapGenerator/Buildings/BuildingGenerator.java
  source/core/src/main/com/deco2800/game/areas/MapGenerator/Buildings/BuildingSpecification.java
  source/core/src/main/com/deco2800/game/areas/MapGenerator/Buildings/CityRow.java
  source/core/src/main/com/deco2800/game/areas/MapGenerator/MapGenerator.java
  source/core/src/main/com/deco2800/game/areas/MapGenerator/ResourceGenerator.java
  source/core/src/main/com/deco2800/game/areas/MapGenerator/pathBuilding/CheckConnectivity.java
  source/core/src/main/com/deco2800/game/areas/MapGenerator/pathBuilding/FindPath.java
  source/core/src/main/com/deco2800/game/areas/MapGenerator/pathBuilding/PathGenerator.java
  source/core/src/main/com/deco2800/game/areas/terrain/AtlantisTerrainFactory.java
  source/core/src/main/com/deco2800/game/areas/terrain/MinimapComponent.java
  source/core/src/main/com/deco2800/game/areas/terrain/TerrainFactory.java
  source/core/src/main/com/deco2800/game/components/building/Building.java
  source/core/src/main/com/deco2800/game/components/building/BuildingActions.java
  source/core/src/main/com/deco2800/game/components/building/GateCollider.java
  source/core/src/main/com/deco2800/game/components/building/TextureScaler.java
  source/core/src/main/com/deco2800/game/components/friendly/FriendlyComponent.java
  source/core/src/main/com/deco2800/game/entities/factories/BuildingFactory.java
  source/core/src/main/com/deco2800/game/entities/factories/UnitFactory.java
  source/core/src/main/com/deco2800/game/input/CameraInputComponent.java
  source/core/src/main/com/deco2800/game/rendering/TextureRenderComponent.java
  source/core/src/main/com/deco2800/game/worker/WorkerFactory.java
  source/core/src/test/com/deco2800/game/areas/BuildingGenerator/BuildingGeneratorTest.java
  source/core/src/test/com/deco2800/game/areas/BuildingGenerator/BuildingSpecificationTest.java
  source/core/src/test/com/deco2800/game/areas/BuildingGenerator/BuildingTest.java
  source/core/src/test/com/deco2800/game/areas/BuildingGenerator/CityRowTest.java
  source/core/src/test/com/deco2800/game/areas/GameAreaTest.java
  source/core/src/test/com/deco2800/game/areas/MapGenerator/MapGeneratorTest.java
  source/core/src/test/com/deco2800/game/areas/MapGenerator/pathBuilding/PathGeneratorTest.java
  source/core/src/test/com/deco2800/game/entities/factories/BuildingFactoryTest.java
Labels: team 6, Sprint 3

#241 Team 7 - Sprint 4
  source/core/assets/images/Sand_Flash.atlas
  source/core/assets/images/Sand_Flash.png
  source/core/src/main/com/deco2800/game/areas/AtlantisGameArea.java
  source/core/src/main/com/deco2800/game/areas/MapGenerator/FloodingGenerator.java
  source/core/src/main/com/deco2800/game/areas/MapGenerator/MapGenerator.java
  source/core/src/main/com/deco2800/game/areas/terrain/AtlantisTerrainFactory.java
  source/core/src/main/com/deco2800/game/components/floodtimer/FloodTimer.java
  source/core/src/main/com/deco2800/game/components/floodtimer/FloodTimerDisplay.java
  source/core/src/main/com/deco2800/game/components/tasks/EnemyMovement.java
  source/core/src/main/com/deco2800/game/utils/random/Timer.java
Labels: team 7, Sprint 4

#251 Team 6 MapService bug fix
  .vscode/settings.json
  source/core/src/main/com/deco2800/game/areas/AtlantisGameArea.java
  source/core/src/main/com/deco2800/game/components/building/TextureScaler.java
  source/core/src/main/com/deco2800/game/entities/factories/BuildingFactory.java
  source/core/src/main/com/deco2800/game/map/MapService.java
  source/core/src/main/com/deco2800/game/rendering/TextureRenderComponent.java
  source/core/src/main/com/deco2800/game/worker/resources/TreeFactory.java
  source/core/src/test/com/deco2800/game/entities/factories/BuildingFactoryTest.java
  source/core/src/test/com/deco2800/game/map/MapServiceTest.java
Labels: team 6, Sprint 4

#252 Team 2 hugh
  source/core/assets/configs/buildings.json
  source/core/assets/images/loading_screen.png
  source/core/src/main/com/deco2800/game/components/HealthBarComponent.java
  source/core/src/main/com/deco2800/game/components/LoadingBar.java
  source/core/src/main/com/deco2800/game/components/building/Building.java
  source/core/src/main/com/deco2800/game/components/gamearea/PerformanceDisplay.java
  source/core/src/main/com/deco2800/game/entities/configs/BlacksmithConfig.java
  source/core/src/main/com/deco2800/game/entities/configs/BuildingConfigs.java
  source/core/src/main/com/deco2800/game/entities/configs/FarmConfig.java
  source/core/src/main/com/deco2800/game/entities/configs/LibraryConfig.java
  source/core/src/main/com/deco2800/game/entities/factories/BuildingFactory.java
  source/core/src/main/com/deco2800/game/screens/LoadingScreen.java
Labels: team 2, Sprint 4

#260 Building UI health bar and stats
  source/core/assets/images/attack.png
  source/core/assets/images/defense.png
  source/core/assets/images/health bar_6.png
  source/core/src/main/com/deco2800/game/components/BuildingUIDataComponent.java
  source/core/src/main/com/deco2800/game/entities/factories/BuildingFactory.java
Labels: team 2, Sprint 2

#264 Team 6 sprint 4: Shop UI + minor fixes
  source/cityMap.txt
  source/core/assets/configs/buildingSpecifications.json
  source/core/assets/configs/shopItems.json
  source/core/assets/images/bush.png
  source/core/assets/images/highlightedBlacksmith.png
  source/core/assets/images/highlightedFarm.png
  source/core/assets/images/highlightedLeftFacingLibrary.png
  source/core/assets/images/highlightedLibrary.png
  source/core/assets/images/highlightedRightFacingLibrary.png
  source/core/assets/images/lamp.png
  source/core/assets/images/lampDefault.png
  source/core/src/main/com/deco2800/game/areas/AtlantisGameArea.java
  source/core/src/main/com/deco2800/game/areas/terrain/AtlantisTerrainFactory.java
  source/core/src/main/com/deco2800/game/components/BuildingUIDataComponent.java
  source/core/src/main/com/deco2800/game/components/building/BuildingActions.java
  source/core/src/main/com/deco2800/game/components/building/ShopUIFunctionalityComponent.java
  source/core/src/main/com/deco2800/game/components/friendlyunits/SelectableComponent.java
  source/core/src/main/com/deco2800/game/components/soldiermenu/SoldierMenuDisplay.java
  source/core/src/main/com/deco2800/game/entities/factories/BuildingFactory.java
  source/core/src/main/com/deco2800/game/entities/factories/CityFeatureFactory.java
  source/core/src/main/com/deco2800/game/rendering/TextureRenderComponent.java
  source/core/src/main/com/deco2800/game/screens/MainGameScreen.java
  source/core/src/main/com/deco2800/game/worker/resources/MiningCampFactory.java
  source/core/src/main/com/deco2800/game/worker/resources/TreeFactory.java
  source/core/src/test/com/deco2800/game/components/building/BuildingActionsTest.java
  source/core/src/test/com/deco2800/game/components/building/ShopUIFunctionalityComponentTest.java
  source/core/src/test/com/deco2800/game/map/MapServiceTest.java
Labels: team 6, Sprint 4

#272 Team 2 sprint 4
  source/core/assets/images/snow1.png
  source/core/assets/images/weather-filter/rain_1.png
  source/core/assets/images/weather-filter/rain_2.png
  source/core/assets/images/weather-filter/rain_3.png
  source/core/assets/sounds/rainsound.mp3
  source/core/assets/sounds/sunny.mp3
  source/core/assets/sounds/thundersound.mp3
  source/core/assets/sounds/winds.mp3
  source/core/src/main/com/deco2800/game/areas/AtlantisGameArea.java
  source/core/src/main/com/deco2800/game/components/BuildingUIDataComponent.java
  source/core/src/main/com/deco2800/game/components/HealthBarComponent.java
  source/core/src/main/com/deco2800/game/components/weather/WeatherIcon.java
  source/core/src/main/com/deco2800/game/components/weather/WeatherIconDisplay.java
  source/core/src/main/com/deco2800/game/components/weather/WeatherIconProperties.java
  source/core/src/main/com/deco2800/game/entities/factories/BuildingFactory.java
  source/core/src/main/com/deco2800/game/screens/LoadingScreen.java
Labels: team 2, Sprint 4

#281 223 team 4 sprint 4 refined buildings
  source/core/assets/images/Trebuchet.atlas
  source/core/assets/images/Trebuchet.png
  source/core/assets/images/barracks.atlas
  source/core/assets/images/barracks.png
  source/core/assets/images/bullet.png
  source/core/assets/images/centre.atlas
  source/core/assets/images/mine.atlas
  source/core/assets/images/mine.png
  source/core/assets/images/ship.atlas
  source/core/assets/images/ship.png
  source/core/assets/images/ship2.atlas
  source/core/assets/images/ship_default.png
  source/core/assets/images/static_trebuchet.png
  source/core/assets/images/titanshrine.atlas
  source/core/assets/images/titanshrine.png
  source/core/assets/images/townHallCentre.atlas
  source/core/assets/images/townHallCentre.png
  source/core/src/main/com/deco2800/game/areas/AtlantisGameArea.java
  source/core/src/main/com/deco2800/game/areas/GameArea.java
  source/core/src/main/com/deco2800/game/areas/RandomPointGenerator.java
  source/core/src/main/com/deco2800/game/areas/TutorialGameArea.java
  source/core/src/main/com/deco2800/game/components/BuildingUIDataComponent.java
  source/core/src/main/com/deco2800/game/components/CombatStatsComponent.java
  source/core/src/main/com/deco2800/game/components/EntityDirection.java
  source/core/src/main/com/deco2800/game/components/TextureImageComponent.java
  source/core/src/main/com/deco2800/game/components/building/AnimationTestingComponent.java
  source/core/src/main/com/deco2800/game/components/building/BuildingAnimationController.java
  source/core/src/main/com/deco2800/game/components/building/BuildingHealth.java
  source/core/src/main/com/deco2800/game/components/building/BuildingHealthManager.java
  source/core/src/main/com/deco2800/game/components/building/DirectionalBuildingAnimationController.java
  source/core/src/main/com/deco2800/game/components/building/HealthAnimation.java
  source/core/src/main/com/deco2800/game/components/building/SelectionCollider.java
  source/core/src/main/com/deco2800/game/components/building/TextureScaler.java
  source/core/src/main/com/deco2800/game/components/building/UpdateBuildingDirection.java
  source/core/src/main/com/deco2800/game/components/building/damageAnimation.java
  source/core/src/main/com/deco2800/game/components/bulletHitShips.java
  source/core/src/main/com/deco2800/game/components/floodtimer/FloodTimerDisplay.java
  source/core/src/main/com/deco2800/game/entities/factories/BuildingFactory.java
  source/core/src/main/com/deco2800/game/entities/factories/EnemyFactory.java
  source/core/src/main/com/deco2800/game/rendering/HighlightedTextureRenderComponent.java
  source/core/src/test/com/deco2800/game/components/building/HealthAnimationTest.java
Labels: Sprint 4
