Repository UQdeco2800/2022-studio-3, pull requests merged in 2022-08, with the labels that each got.

#49 Team 6 map feature
  .gitignore
  source/core/assets/images/Grass.piskel
  source/core/assets/images/Grass.png
  source/core/assets/images/Ocean.piskel
  source/core/assets/images/Ocean.png
  source/core/assets/images/README.md
  source/core/assets/images/Sand.piskel
  source/core/assets/images/Sand.png
  source/core/assets/images/Tree.piskel
  source/core/assets/images/Tree_max.png
  source/core/src/main/com/deco2800/game/areas/AtlantisGameArea.java
  source/core/src/main/com/deco2800/game/areas/ForestGameArea.java
  source/core/src/main/com/deco2800/game/areas/MapGenerator/Coordinate.java
  source/core/src/main/com/deco2800/game/areas/MapGenerator/MapGenerator.java
  source/core/src/main/com/deco2800/game/areas/terrain/AtlantisTerrainFactory.java
  source/core/src/main/com/deco2800/game/areas/terrain/TerrainComponent.java
  source/core/src/main/com/deco2800/game/areas/terrain/TerrainFactory.java
  source/core/src/main/com/deco2800/game/components/CameraComponent.java
  source/core/src/main/com/deco2800/game/entities/factories/RenderFactory.java
  source/core/src/main/com/deco2800/game/input/CameraInputComponent.java
  source/core/src/main/com/deco2800/game/input/InputFactory.java
  source/core/src/main/com/deco2800/game/input/KeyboardInputFactory.java
  source/core/src/main/com/deco2800/game/input/TouchInputFactory.java
  source/core/src/main/com/deco2800/game/screens/MainGameScreen.java
  source/core/src/test/com/deco2800/game/areas/MapGenerator/MapGeneratorTest.java
  source/core/src/test/com/deco2800/game/areas/terrain/TerrainComponentTest.java
Labels: feature, team 6, Sprint 1

#55 Team4 sprint one enemy units
  source/.idea.template/workspace.xml
  source/core/assets/configs/NPCs.json
  source/core/assets/images/blue_joker.atlas
  source/core/assets/images/blue_joker.png
  source/core/assets/images/snake.atlas
  source/core/assets/images/snake.png
  source/core/assets/images/wolf.atlas
  source/core/assets/images/wolf.png
  source/core/src/main/com/deco2800/game/areas/ForestGameArea.java
  source/core/src/main/com/deco2800/game/components/player/PlayerStatsDisplay.java
  source/core/src/main/com/deco2800/game/components/tasks/AIHorizontalMovement.java
  source/core/src/main/com/deco2800/game/components/tasks/AIVerticalMovementTask.java
  source/core/src/main/com/deco2800/game/components/tasks/EnemyMovementTask.java
  source/core/src/main/com/deco2800/game/components/tasks/rangedAttackTask.java
  source/core/src/main/com/deco2800/game/entities/configs/NPCConfigs.java
  source/core/src/main/com/deco2800/game/entities/factories/NPCFactory.java
Labels: feature, team 4, Sprint 1

#61 Menu Intro Song
  source/core/assets/sounds/menu.wav
  source/core/src/main/com/deco2800/game/areas/AtlantisGameArea.java
  source/core/src/main/com/deco2800/game/screens/MainMenuScreen.java
Labels: feature, team 3

#63 Team 2 hugh
  assets/wiki/buildings/A-Township-Tale-Blacksmith-Guide-1.jpg
  assets/wiki/buildings/AOE-barracks-inspo.png
  assets/wiki/buildings/Atlantis City Centre.jpg
  assets/wiki/buildings/barracks atlantis.png
  assets/wiki/buildings/barracks medieval.png
  assets/wiki/buildings/barracks-inspo-irl-topdown.png
  assets/wiki/buildings/barracks-inspo-irl.png
  assets/wiki/buildings/barracks_iso_sketch.png
  assets/wiki/buildings/barracks_iso_water_sketch.png
  assets/wiki/buildings/barracks_sketch_topdown.png
  assets/wiki/buildings/barracks_topdown.png
  assets/wiki/buildings/building_topdown.png
  assets/wiki/buildings/buliding_topdown_sketch.png
  assets/wiki/buildings/city-centre-inspo-1.jpg
  assets/wiki/buildings/city-centre-inspo.jpg
  assets/wiki/buildings/heritage-blinman-mine.jpg
  assets/wiki/buildings/inspiration.jpg
  assets/wiki/buildings/isometric barracks current.png
  assets/wiki/buildings/mining.png
  assets/wiki/buildings/poseidon-atlantian-barracks-inspo.png
  assets/wiki/buildings/rts.png
  assets/wiki/buildings/wall-1.jpg
  assets/wiki/buildings/wall-2.jpg
  source/core/assets/configs/buildings.json
  source/core/assets/images/Base.png
  source/core/assets/images/barracks atlantis.png
  source/core/assets/images/barracks medieval.png
  source/core/assets/images/isometric barracks current.png
  source/core/assets/images/wall_1.png
  source/core/assets/images/wall_2.png
  source/core/src/main/com/deco2800/game/areas/AtlantisGameArea.java
  source/core/src/main/com/deco2800/game/areas/ForestGameArea.java
  source/core/src/main/com/deco2800/game/components/building/BuildingActions.java
  source/core/src/main/com/deco2800/game/components/gamearea/PerformanceDisplay.java
  source/core/src/main/com/deco2800/game/components/player/TouchPlayerInputComponent.java
  source/core/src/main/com/deco2800/game/entities/configs/BarracksConfig.java
  source/core/src/main/com/deco2800/game/entities/configs/BuildingConfigs.java
  source/core/src/main/com/deco2800/game/entities/configs/TownHallConfig.java
  source/core/src/main/com/deco2800/game/entities/configs/WallConfig.java
  source/core/src/main/com/deco2800/game/entities/factories/BuildingFactory.java
  source/core/src/main/com/deco2800/game/services/ServiceLocator.java
Labels: team 2, Sprint 1
