Repository UQdeco2800/2022-studio-3, pull requests merged in 2022-09, with the labels that each got.

#107 Team 6 - Minimap Texturing
  source/core/assets/test/files/dummyOcean.png
  source/core/assets/test/files/dummyTexture.png
  source/core/src/main/com/deco2800/game/areas/AtlantisGameArea.java
  source/core/src/main/com/deco2800/game/areas/terrain/MinimapComponent.java
  source/core/src/main/com/deco2800/game/screens/MainMenuScreen.java
Labels: team 6

#108 Advanced Buildings Part 1
  .DS_Store
  assets/wiki/buildings/barracks_level_1.0.png
  assets/wiki/buildings/barracks_level_1.1.png
  assets/wiki/buildings/barracks_level_1.2.png
  assets/wiki/buildings/barracks_level_2.0.png
  assets/wiki/buildings/mining_levelone_sketch.png
  assets/wiki/buildings/mining_leveltwo_sketch.png
  source/core/assets/images/barracks atlantis.png
  source/core/assets/images/barracks medieval.png
  source/core/assets/images/barracks_level_1.0.png
  source/core/assets/images/barracks_level_1.1.png
  source/core/assets/images/barracks_level_1.2.png
  source/core/assets/images/barracks_level_2.0.png
  source/core/assets/images/isometric barracks current.png
  source/core/assets/images/level 1 town hall.png
  source/core/assets/images/level 2 town hall.png
  source/core/assets/images/mining_levelone_sketch.png
  source/core/assets/images/mining_leveltwo_sketch.png
  source/core/assets/images/stone_wall.png
  source/core/assets/images/stone_wall_1.png
  source/core/assets/images/stone_wall_2_.png
  source/core/assets/images/stone_wall_3.png
  source/core/assets/images/stone_wall_4.png
  source/core/assets/images/wooden_wall.png
  source/core/assets/images/wooden_wall_1.png
  source/core/assets/images/wooden_wall_2.png
  source/core/assets/images/wooden_wall_3.png
  source/core/assets/images/wooden_wall_4.png
  source/core/src/main/com/deco2800/game/areas/AtlantisGameArea.java
  source/core/src/main/com/deco2800/game/areas/ForestGameArea.java
  source/core/src/main/com/deco2800/game/areas/GameArea.java
  source/core/src/main/com/deco2800/game/components/building/Building.java
  source/core/src/main/com/deco2800/game/components/building/BuildingActions.java
  source/core/src/main/com/deco2800/game/components/friendlyunits/SelectableComponent.java
  source/core/src/main/com/deco2800/game/components/gamearea/PerformanceDisplay.java
  source/core/src/main/com/deco2800/game/components/maingame/InfoBoxDisplay.java
  source/core/src/main/com/deco2800/game/components/player/TouchPlayerInputComponent.java
  source/core/src/main/com/deco2800/game/entities/configs/BarracksConfig.java
  source/core/src/main/com/deco2800/game/entities/configs/TownHallConfig.java
  source/core/src/main/com/deco2800/game/entities/configs/WallConfig.java
  source/core/src/main/com/deco2800/game/entities/factories/BuildingFactory.java
  source/core/src/main/com/deco2800/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/deco2800/game/physics/PhysicsUtils.java
  source/core/src/main/com/deco2800/game/rendering/RenderComponent.java
  source/core/src/main/com/deco2800/game/rendering/Renderer.java
  source/core/src/main/com/deco2800/game/rendering/TextureRenderComponent.java
  source/core/src/main/com/deco2800/game/ui/terminal/TerminalDisplay.java
  source/core/src/main/com/deco2800/game/utils/random/Timer.java
  source/core/src/test/com/deco2800/game/components/building/BuildingActionsTest.java
Labels: team 2, Sprint 2

#123 Team 1 Sprint 2
  source/core/assets/images/Base_Highlight.png
  source/core/assets/images/barracks_level_1.0_Highlight.png
  source/core/assets/images/barracks_level_1.0_highlight.png
  source/core/assets/images/barracks_level_1.1_Highlight.png
  source/core/assets/images/barracks_level_1.1_highlight.png
  source/core/assets/images/barracks_level_1.2_Highlight.png
  source/core/assets/images/barracks_level_1.2_highlight.png
  source/core/assets/images/barracks_level_2.0_Highlight.png
  source/core/assets/images/barracks_level_2.0_highlight.png
  source/core/assets/images/box_boy_highlight.png
  source/core/assets/images/level 2 town hall Highlight.png
  source/core/assets/images/level 2 town hall_Highlight.png
  source/core/assets/images/level_1_town_hall Highlight.png
  source/core/assets/images/level_1_town_hall_Highlight.png
  source/core/src/main/com/deco2800/game/areas/AtlantisGameArea.java
  source/core/src/main/com/deco2800/game/components/friendlyunits/GestureDisplay.java
  source/core/src/main/com/deco2800/game/components/friendlyunits/MouseInputComponent.java
  source/core/src/main/com/deco2800/game/components/friendlyunits/SelectableComponent.java
  source/core/src/main/com/deco2800/game/components/maingame/InfoBoxDisplay.java
  source/core/src/main/com/deco2800/game/entities/factories/BuildingFactory.java
  source/core/src/main/com/deco2800/game/entities/factories/PlayerFactory.java
  source/core/src/main/com/deco2800/game/input/CameraInputComponent.java
  source/core/src/main/com/deco2800/game/rendering/HighlightedTextureRenderComponent.java
  source/core/src/main/com/deco2800/game/rendering/TextureRenderComponent.java
Labels: team 1, Sprint 2

#130 Team5 - Sprint 2 - Pause menu - Cutscene Sketch
  source/core/assets/images/Scene2Cut3.png
  source/core/src/main/com/deco2800/game/components/maingame/MainGameExitDisplay.java
  source/core/src/main/com/deco2800/game/input/CameraInputComponent.java
  source/core/src/main/com/deco2800/game/services/GameTime.java
Labels: team 5, Sprint 2

#132 Team 2 sprint 2
  assets/wiki/buildings/mining_camp_sketch.png
  source/core/src/main/com/deco2800/game/areas/AtlantisGameArea.java
  source/core/src/main/com/deco2800/game/components/building/Building.java
  source/core/src/main/com/deco2800/game/components/building/BuildingActions.java
  source/core/src/main/com/deco2800/game/components/friendlyunits/SelectableComponent.java
  source/core/src/main/com/deco2800/game/components/maingame/InfoBoxDisplay.java
  source/core/src/main/com/deco2800/game/entities/factories/BuildingFactory.java
  source/core/src/test/com/deco2800/game/components/building/BuildingActionsTest.java
  source/core/src/test/com/deco2800/game/entities/factories/BuildingFactoryTest.java
Labels: team 2, Sprint 2

#136 Team5 - Sprint 2 - cutscenes
  source/core/assets/images/Cutscene2.png
  source/core/assets/images/Cutscene4.png
  source/core/assets/images/cutscene1.png
Labels: Sprint 2

#137 Team 7
  source/core/assets/images/Moon.piskel
  source/core/assets/images/Potion.piskel
  source/core/assets/images/Rainy.piskel
  source/core/assets/images/Snowy.piskel
  source/core/assets/images/Sun.piskel
  source/core/assets/images/cloudy.atlas
  source/core/assets/images/cloudyatlas.png
  source/core/assets/images/cloudybackground.png
  source/core/assets/images/cloudyeffect.png
  source/core/assets/images/foggy.png
  source/core/assets/images/heavyrain.png
  source/core/assets/images/hoplite.atlas
  source/core/assets/images/partlycloudy.png
  source/core/assets/images/rainy.atlas
  source/core/assets/images/rainy.gif
  source/core/assets/images/rainyeffect.png
  source/core/assets/images/snowy.atlas
  source/core/assets/images/snowy.gif
  source/core/assets/images/snowyeffect.png
  source/core/assets/images/spearman.atlas
  source/core/assets/images/sunny.atlas
  source/core/assets/images/sunnyatlas.png
  source/core/assets/images/thundereffect.gif
  source/core/assets/images/thundereffect.png
  source/core/assets/images/thunderstorm.atlas
  source/core/assets/images/thunderstorm.gif
  source/core/assets/images/weather-filter/cloudy-filter.png
  source/core/assets/images/weather-filter/rainy-filter.png
  source/core/assets/images/weather-filter/snowy-filter.png
  source/core/assets/images/weather-filter/sunny-filter.png
  source/core/assets/images/weather-filter/thunderstorm-filter.png
  source/core/src/main/com/deco2800/game/components/player/PlayerActions.java
  source/core/src/main/com/deco2800/game/components/weather/WeatherIcon.java
  source/core/src/main/com/deco2800/game/components/weather/WeatherIconDisplay.java
  source/core/src/main/com/deco2800/game/components/weather/WeatherIconProperties.java
  source/core/src/main/com/deco2800/game/entities/EntityService.java
  source/core/src/main/com/deco2800/game/physics/components/PhysicsMovementComponent.java
  source/core/src/main/com/deco2800/game/worker/components/movement/WorkerMovementTask.java
  source/core/src/test/com/deco2800/game/components/weather/WeatherIconDisplayTest.java
  source/core/src/test/com/deco2800/game/components/weather/WeatherIconTest.java
  source/core/src/test/com/deco2800/game/utils/random/TimerTest.java
Labels: Sprint 2

#147 improved titan attack and increased size to 256
  source/core/assets/images/titan.atlas
  source/core/assets/images/titan.png
Labels: team 4, Sprint 2
